#line 2 "verilog_lexer.cc"

#line 4 "verilog_lexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer frontend_verilog_yy_create_buffer
#define yy_delete_buffer frontend_verilog_yy_delete_buffer
#define yy_flex_debug frontend_verilog_yy_flex_debug
#define yy_init_buffer frontend_verilog_yy_init_buffer
#define yy_flush_buffer frontend_verilog_yy_flush_buffer
#define yy_load_buffer_state frontend_verilog_yy_load_buffer_state
#define yy_switch_to_buffer frontend_verilog_yy_switch_to_buffer
#define yyin frontend_verilog_yyin
#define yyleng frontend_verilog_yyleng
#define yylex frontend_verilog_yylex
#define yylineno frontend_verilog_yylineno
#define yyout frontend_verilog_yyout
#define yyrestart frontend_verilog_yyrestart
#define yytext frontend_verilog_yytext
#define yywrap frontend_verilog_yywrap
#define yyalloc frontend_verilog_yyalloc
#define yyrealloc frontend_verilog_yyrealloc
#define yyfree frontend_verilog_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE frontend_verilog_yyrestart(frontend_verilog_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t frontend_verilog_yyleng;

extern FILE *frontend_verilog_yyin, *frontend_verilog_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE frontend_verilog_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-frontend_verilog_yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < frontend_verilog_yyleng; ++yyl )\
                    if ( frontend_verilog_yytext[yyl] == '\n' )\
                        --frontend_verilog_yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --frontend_verilog_yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up frontend_verilog_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up frontend_verilog_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via frontend_verilog_yyrestart()), so that the user can continue scanning by
	 * just pointing frontend_verilog_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when frontend_verilog_yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t frontend_verilog_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow frontend_verilog_yywrap()'s to do buffer switches
 * instead of setting up a fresh frontend_verilog_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void frontend_verilog_yyrestart (FILE *input_file  );
void frontend_verilog_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE frontend_verilog_yy_create_buffer (FILE *file,int size  );
void frontend_verilog_yy_delete_buffer (YY_BUFFER_STATE b  );
void frontend_verilog_yy_flush_buffer (YY_BUFFER_STATE b  );
void frontend_verilog_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void frontend_verilog_yypop_buffer_state (void );

static void frontend_verilog_yyensure_buffer_stack (void );
static void frontend_verilog_yy_load_buffer_state (void );
static void frontend_verilog_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER frontend_verilog_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE frontend_verilog_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE frontend_verilog_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE frontend_verilog_yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *frontend_verilog_yyalloc (yy_size_t  );
void *frontend_verilog_yyrealloc (void *,yy_size_t  );
void frontend_verilog_yyfree (void *  );

#define yy_new_buffer frontend_verilog_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        frontend_verilog_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            frontend_verilog_yy_create_buffer(frontend_verilog_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        frontend_verilog_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            frontend_verilog_yy_create_buffer(frontend_verilog_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define frontend_verilog_yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *frontend_verilog_yyin = (FILE *) 0, *frontend_verilog_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int frontend_verilog_yylineno;

int frontend_verilog_yylineno = 1;

extern char *frontend_verilog_yytext;
#define yytext_ptr frontend_verilog_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up frontend_verilog_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	frontend_verilog_yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[569] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  116,  114,  110,  110,  110,  114,   57,  114,
       67,  114,  114,  114,  114,  114,  114,  114,   53,  114,
      114,  114,   67,  114,  114,  114,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,  114,  114,  114,  107,  108,  107,
       60,  115,   59,   60,   69,   70,   69,   69,   75,   75,
       75,   75,   81,   79,   79,   78,   80,    0,    0,   91,
      113,   67,   67,   67,   67,   67,   67,   89,    0,    0,
       83,   84,   87,   86,  104,  105,  106,  112,    0,   53,

        0,    0,  100,   92,   90,   93,  101,   82,  111,   99,
        7,    7,    7,    7,    7,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   22,   67,
       67,   67,   67,   67,   67,   67,   27,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   85,
       88,   96,   98,   97,  109,   58,    0,    0,    0,   76,
        0,    0,   78,   95,   67,   67,   67,   67,   67,   67,
        0,   54,    0,    0,  112,   55,    0,   56,  102,   94,
      103,    7,    7,    7,    7,    7,   67,   61,   67,   67,
       43,   61,   67,   67,   67,   21,   24,   67,   67,   67,

       67,   67,   67,   67,   67,   67,   67,   67,   67,   61,
       67,   67,   67,   67,   67,   48,   67,   67,   67,   67,
       67,   67,   67,    0,    0,    0,    0,    0,    0,   67,
       67,   67,   67,   67,   67,    0,   55,    0,    7,    7,
        7,    7,   67,   67,   67,   67,   67,   28,   67,   67,
       23,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   52,   67,   67,   67,   12,   67,   47,
        0,    0,    0,    0,    0,   67,   67,   67,   64,   67,
        0,    0,   55,    7,    7,    7,    7,   67,   67,   67,

       20,   67,   29,   30,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   46,   44,   67,   67,
       42,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   35,    0,    0,    0,    0,    0,   67,   67,   67,
       67,    0,    0,    7,    7,    0,    7,   18,   40,   17,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   51,
       67,   67,   67,   67,    8,   67,   45,   67,   67,   67,
       36,   50,   67,    0,    0,    0,    0,    0,   67,   65,
       67,    0,    0,    7,    7,    7,    0,    7,   67,   32,
       67,   31,   67,   67,   67,   13,   67,   67,    0,   19,

       49,   67,   26,   67,   25,   67,   62,   63,    0,    0,
        0,    0,    0,   67,    0,    0,    7,    7,    7,    7,
        0,    7,   67,   67,   67,   16,   67,   67,   67,   10,
       33,    0,   67,   67,   41,    0,    0,    0,    0,    0,
        0,   66,    0,    0,    7,    7,    7,    7,    0,    7,
       67,   38,   67,   67,   67,    9,    0,   67,   14,    0,
        0,    0,    0,   73,    0,    0,    0,    7,    7,    0,
        2,    7,    7,    0,    7,   67,   67,   67,   67,    0,
       15,    0,    0,    0,    0,   72,    0,    7,    7,    1,
        0,    0,   37,   67,   11,   34,    0,    0,    0,    0,

        0,    7,    7,    1,    0,    3,    0,    0,    0,   39,
        0,    0,    0,    0,    0,    7,    7,    0,    5,    0,
        0,    0,   74,    0,    7,    7,    5,    5,    0,    0,
        0,    7,    4,    0,    0,    0,    7,    4,    0,    0,
        0,    0,    0,    0,    0,    6,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   77,    0,
        0,    0,    0,    0,    0,   71,   68,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    1,   10,   11,   12,
       13,   14,   15,    1,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   29,   30,   31,   28,
       32,   32,   33,   32,   32,   32,   32,   32,   32,   34,
       32,   32,   32,   32,   32,   32,   32,   28,   32,   28,
        1,   35,    1,   36,   37,   38,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   32,   48,   49,   50,   51,
       52,   53,   32,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    2,    3,    4,    5,    1,    1,    1,    6,    1,
        1,    1,    1,    1,    1,    1,    7,    8,    9,    9,
        9,    1,    1,    1,    1,    1,   10,   11,   11,   11,
       11,    6,    6,    6,    1,    1,   11,    1,   11,   11,
       11,   11,   11,   11,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,   11,
        6,   11,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[592] =
    {   0,
        0,    0,   64,   65,   66,   67,   68,   69,   74,   77,
      130,    0, 1053, 1054,   79, 1054, 1054, 1027, 1054,    0,
       41, 1041,   53, 1036,  184, 1027, 1026,   86,  248,   51,
     1022,   84,    0,  108,  980,   73,   65,  156, 1006, 1001,
       43,   67, 1000,  156,  990,  989,  162,   69,  163,  997,
       56, 1000,  162,  159, 1024,  973,  194, 1054, 1054, 1018,
     1054, 1054, 1054,    0, 1054, 1054, 1021,  172, 1054, 1016,
      976,  993, 1054, 1054, 1054,    0, 1054,  217,  183, 1006,
        0,    0,  983,  982,  171,  981,  976, 1054,  229,  199,
     1054, 1054, 1054, 1054, 1054, 1054,  235,    0,  223,    0,

      241,  255, 1002, 1054, 1000, 1054,  998,  243, 1054, 1054,
        0,  980,  975,  974,  973,  960,  976,  962,  971,  959,
      970,  958,  968,  956,  968,  955,  957,  956,    0,  953,
      241,  179,  963,  953,  958,  198,    0,  946,  947,  945,
      947,  242,  953,  944,  941,  948,  940,  941,  938, 1054,
     1054, 1054, 1054, 1054, 1054, 1054,  261,  944,  943, 1054,
      940,  934,    0, 1054,  932,  935,  940,  932,  933,  927,
      297,  301,  268,  920,    0,  288,  291,  301, 1054, 1054,
     1054,    0,  936,  930,  927,  927,  937,    0,  237,  928,
        0,  927,  930,  173,  929,  285,    0,  930,  274,  918,

      913,  911,  910,  923,  926,  917,  906,  920,  918,  913,
      906,  919,  914,  903,  906,    0,  911,  902,  899,  903,
      901,  906,  894,  313,  886,  897,  894,  895,  904,  889,
      894,  889,  886,  895,  890,  885,  323,  330,  896,  891,
      890,  889,  870,  876,  884,  877,  883,  274,  869,  886,
        0,  885,  866,  879,  869,  881,  863,  864,  878,  862,
      868,  858,  857,  867,  862,  869,  860,  866,  863,  849,
      855,  862,  860,    0,  863,  858,  851,    0,  856,    0,
      847,  854,  853,  858,  845,  844,  837,  848,    0,  845,
      281,  336,  342,  832,  851,  123,  832,  831,  829,  833,

        0,  263,    0,    0,  834,  828,  826,  829,  828,  836,
      822,  829,  836,  820,  817,  833,    0,    0,  828,  817,
        0,  826,  823,  294,  811,  823,  820,  810,  807,  820,
      800,    0,  296,  823,  322,  818,  809,  818,  810,  813,
      803,  800,  806,  802,  318,  370,  809,  812,    0,    0,
      792,  808,  803,  804,  801,  786,  794,  789,  784,    0,
      378,  790,  784,  798,    0,  793,    0,  779,  791,  777,
        0,    0,  320,  779,  785,  777,  790,  785,  766,    0,
      783,  770,  781,  767,  770,  301,  372,  782,  343,    0,
      770,    0,  763,  764,  768,    0,  765,  772,  386,    0,

        0,  760,    0,  770,    0,  751,    0,    0,  756,  767,
      307,  754,  759,  765,  745,  750,  767,  747,  749,  746,
      392,  751,  747,  754,  758,    0,  749,  756,  751,    0,
        0,  763,  753,  737,    0,  729,  734,  735,  732,  743,
      748,    0,  729,  736,  731,  737,  399,  734,    0,  736,
      725,    0,  715,  718,  703,    0,  715,  698,    0,  683,
      684,  724,  680, 1054,  675,  464,  649,  641,  631,  679,
     1054,    0,  667,  664,  393,  627,  624,  613,  612,  621,
        0,  465,  593,  642,  607,  466,  586,  582,  580,    0,
      469,  473,    0,  581,    0,    0,  248,  475,  569,  567,

      582,  564,  561,    0,  476, 1054,  606,  479,  483,    0,
      487,  577,  565,  560,  549,  537,  508,  491,  492,  500,
      542,  497, 1054,  488,  488,  535,  493,  505,  475,  464,
      469,  474,    0,  463,  457,  461,  506,    0,  458,  448,
      417,  510,  340,  330,  342,  511,  331,  333,  333,  313,
      310,  244,  238,  225,  227,  521,  197,  192,  525,  531,
      532,  533,   71,  537,   64, 1054, 1054, 1054,  551,  562,
      573,  584,  590,  596,  607,  613,  624,  630,  640,  651,
      657,  668,  679,  690,  701,  712,  723,  734,  745,  756,
      767

    } ;

static yyconst flex_int16_t yy_def[592] =
    {   0,
      568,    1,  569,  569,  570,  570,  571,  571,  572,  572,
      568,   11,  568,  568,  568,  568,  568,  568,  568,  573,
      574,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  574,  575,  568,  576,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  577,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  578,  568,  568,  568,  568,
      573,  574,  574,  574,  574,  574,  574,  568,  579,  568,
      568,  568,  568,  568,  568,  568,  568,  580,  568,   29,

      568,  568,  568,  568,  568,  568,  568,  575,  568,  568,
      581,  581,  581,  581,  581,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  578,  568,  574,  574,  574,  574,  574,  574,
      579,  579,  568,  568,  580,  568,  568,  568,  568,  568,
      568,  581,  581,  581,  581,  581,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,

      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  568,  568,  568,  568,  568,  568,  574,
      574,  574,  574,  574,  574,  568,  568,  568,  581,  581,
      581,  581,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      568,  568,  568,  568,  568,  574,  574,  574,  574,  574,
      568,  568,  568,  581,  581,  581,  581,  574,  574,  574,

      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  568,  568,  568,  568,  568,  574,  574,  574,
      574,  568,  568,  581,  581,  582,  581,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  568,  568,  568,  568,  568,  574,  574,
      574,  568,  568,  581,  581,  581,  582,  581,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  568,  574,

      574,  574,  574,  574,  574,  574,  574,  574,  568,  568,
      568,  568,  568,  574,  568,  568,  581,  581,  581,  581,
      568,  581,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  568,  574,  574,  574,  568,  568,  568,  568,  568,
      568,  574,  568,  568,  581,  581,  568,  581,  583,  581,
      574,  574,  574,  574,  574,  574,  568,  574,  574,  568,
      568,  584,  568,  568,  568,  568,  568,  581,  581,  584,
      568,  447,  581,  583,  581,  574,  574,  574,  574,  568,
      574,  568,  568,  568,  568,  568,  568,  581,  581,  585,
      586,  587,  574,  574,  574,  574,  568,  568,  568,  568,

      568,  581,  581,  585,  586,  568,  588,  586,  587,  574,
      568,  568,  568,  568,  568,  581,  581,  568,  589,  568,
      568,  568,  568,  568,  581,  581,  589,  589,  568,  568,
      568,  581,  590,  568,  568,  568,  581,  590,  568,  568,
      568,  591,  568,  568,  568,  591,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,    0,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568

    } ;

static yyconst flex_int16_t yy_nxt[1121] =
    {   0,
       14,   15,   16,   17,   15,   18,   19,   20,   21,   22,
       23,   24,   14,   25,   26,   27,   14,   28,   29,   29,
       29,   14,   14,   30,   31,   32,   14,   33,   33,   33,
       33,   33,   33,   33,   34,   35,   33,   36,   37,   38,
       39,   40,   41,   42,   43,   33,   44,   33,   45,   46,
       47,   48,   49,   50,   51,   52,   33,   33,   53,   54,
       33,   33,   55,   56,   14,   57,   59,   59,   62,   62,
       66,   66,   63,   63,  103,  104,   62,   60,   60,   62,
       78,  567,   83,   78,   84,   67,   67,   70,  566,   79,
       70,  124,   89,  125,   89,   85,   86,   87,   89,   97,

       64,   64,  143,   98,   89,   68,   68,   90,  106,  107,
      109,  109,  144,  116,  112,  117,  113,   71,  126,  118,
       71,  114,  137,  127,  346,  138,   72,  346,  115,   72,
       73,   74,   75,   74,   74,   73,   73,   73,   76,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   77,   73,   73,   73,   73,   76,   76,   76,
       76,   76,   76,   76,   73,   73,   76,   73,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   73,   73,   73,   73,   92,   93,  119,  129,

      134,  139,  120,  152,  135,  130,  131,  146,  147,  148,
      149,  249,  121,  136,  140,  158,  141,  167,   78,  205,
      159,   78,   89,  206,   89,  250,  168,   79,   89,  153,
      171,  171,  171,  171,   89,  561,  173,   90,   89,  173,
       89,  176,  176,  176,   89,  568,  568,  560,   94,   78,
       89,  188,   78,  210,  511,  177,  177,  154,   79,  178,
      178,  178,  224,  512,   99,  224,  100,  100,  100,  173,
      558,   99,  173,  102,  102,  102,  557,  178,  101,  244,
      215,  188,  188,  245,  102,  101,  216,  201,  556,  174,
      101,  102,  202,  203,  217,  555,  204,  101,  171,  171,

      171,  171,  568,  568,  568,  568,  237,  237,  237,  178,
      178,  178,  188,  188,  224,  225,  258,  224,  238,  178,
      178,  178,  174,  346,  237,  252,  346,  178,  253,  254,
      238,  259,  342,  303,  255,  304,  343,  178,  407,  408,
      256,  237,  237,  237,  292,  292,  554,  374,  293,  293,
      293,  375,  419,  238,  293,  293,  293,  420,  438,  237,
      293,  293,  293,  439,  553,  238,  293,  225,  385,  552,
      386,  346,  293,  421,  346,  551,  421,  550,  293,  399,
      399,  399,  399,  423,  549,  548,  424,  399,  399,  399,
      399,  425,  432,  421,  492,  547,  421,  492,  449,  470,

      470,  471,  470,  470,  470,  470,  470,  472,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  472,  472,  472,
      470,  470,  470,  470,  470,  470,  472,  472,  472,  472,
      472,  472,  472,  470,  470,  472,  470,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  470,  470,  470,  470,  486,  498,  486,  486,  498,
      486,  506,  545,  507,  492,  508,  498,  492,  506,  498,
      507,  506,  508,  507,  518,  508,  544,  518,  520,  520,
      520,  520,  518,  528,  568,  518,  528,  568,  543,  541,

      519,  520,  520,  520,  520,  540,  528,  542,  519,  528,
      542,  542,  568,  539,  542,  568,  537,  536,  535,  487,
      499,  487,  559,  559,  559,  559,  559,  559,  559,  559,
      499,  534,  562,  564,  562,  562,  564,  562,  564,  533,
      532,  564,  531,  529,  563,  565,  563,  530,  511,  526,
      565,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   81,   81,  525,   81,  524,

       81,   82,  523,  522,   82,  521,   82,  108,  506,  108,
      108,  517,  108,  108,  108,  108,  108,  108,  111,  516,
      515,  514,  513,  111,  156,  156,  510,  156,  156,  156,
      156,  156,  156,  156,  156,  163,  503,  502,  163,  501,
      163,  172,  172,  172,  172,  500,  490,  482,  172,  172,
      172,  175,  175,  497,  496,  175,  175,  175,  175,  175,
      175,  175,  182,  495,  494,  182,  493,  182,  387,  387,
      491,  490,  387,  387,  387,  387,  387,  387,  387,  474,
      474,  471,  489,  488,  474,  474,  474,  474,  474,  474,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,

      470,  504,  504,  466,  504,  504,  504,  504,  504,  504,
      504,  504,  505,  505,  505,  485,  505,  505,  505,  505,
      505,  505,  505,  509,  509,  484,  471,  509,  509,  509,
      483,  509,  509,  509,  507,  507,  507,  482,  507,  507,
      507,  507,  507,  507,  507,  527,  527,  481,  480,  527,
      527,  527,  527,  527,  527,  527,  538,  538,  479,  538,
      538,  538,  538,  538,  538,  538,  538,  546,  546,  478,
      477,  546,  546,  546,  476,  546,  546,  546,  475,  473,
      469,  468,  467,  466,  465,  464,  463,  462,  461,  460,
      459,  458,  457,  456,  455,  454,  453,  452,  451,  450,

      448,  447,  446,  445,  444,  443,  442,  441,  440,  437,
      436,  435,  434,  433,  431,  430,  429,  428,  427,  426,
      422,  418,  417,  416,  415,  414,  289,  413,  412,  411,
      410,  409,  406,  405,  404,  403,  402,  401,  400,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      384,  383,  382,  381,  380,  289,  379,  378,  377,  376,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  345,  344,  341,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,

      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  291,  290,  289,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  188,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  188,  267,  266,  265,  264,  263,  262,  261,  260,
      257,  251,  248,  247,  246,  243,  242,  241,  240,  239,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  188,  223,  222,  221,  220,  219,  218,  214,  213,

      212,  211,  209,  208,  207,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  181,  180,  179,  170,  169,  166,  165,
      164,  162,  161,  160,  157,  155,  151,  150,  145,  142,
      133,  132,  128,  123,  122,  110,  105,   96,   95,   91,
       88,   80,  568,   13,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,

      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568
    } ;

static yyconst flex_int16_t yy_chk[1121] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    5,    6,
        7,    8,    5,    6,   30,   30,    9,    3,    4,   10,
       15,  565,   21,   15,   21,    7,    8,    9,  563,   15,
       10,   41,   23,   41,   23,   21,   21,   21,   23,   28,

        5,    6,   51,   28,   23,    7,    8,   23,   32,   32,
       34,   34,   51,   37,   36,   37,   36,    9,   42,   37,
       10,   36,   48,   42,  296,   48,    9,  296,   36,   10,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   25,   25,   38,   44,

       47,   49,   38,   57,   47,   44,   44,   53,   53,   54,
       54,  194,   38,   47,   49,   68,   49,   85,   78,  132,
       68,   78,   79,  132,   79,  194,   85,   78,   79,   57,
       89,   89,   89,   89,   79,  558,   97,   79,   90,   97,
       90,   99,   99,   99,   90,  108,  108,  557,   25,   29,
       90,  136,   29,  136,  497,  101,  101,   57,   29,  101,
      101,  101,  157,  497,   29,  157,   29,   29,   29,  173,
      555,  102,  173,  102,  102,  102,  554,  101,   29,  189,
      142,  302,  302,  189,   29,  102,  142,  131,  553,   97,
       29,  102,  131,  131,  142,  552,  131,  102,  171,  171,

      171,  171,  172,  172,  172,  172,  176,  176,  176,  177,
      177,  177,  324,  324,  224,  157,  199,  224,  176,  178,
      178,  178,  173,  335,  176,  196,  335,  177,  196,  196,
      176,  199,  291,  248,  196,  248,  291,  178,  373,  373,
      196,  237,  237,  237,  238,  238,  551,  333,  238,  238,
      238,  333,  386,  237,  292,  292,  292,  386,  411,  237,
      293,  293,  293,  411,  550,  237,  238,  224,  345,  549,
      345,  346,  292,  387,  346,  548,  387,  547,  293,  361,
      361,  361,  361,  389,  545,  544,  389,  399,  399,  399,
      399,  389,  399,  421,  475,  543,  421,  475,  421,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  466,  482,  486,  466,  482,
      486,  491,  541,  491,  492,  491,  498,  492,  505,  498,
      505,  508,  505,  508,  509,  508,  540,  509,  511,  511,
      511,  511,  518,  519,  527,  518,  519,  527,  539,  536,

      509,  520,  520,  520,  520,  535,  528,  537,  518,  528,
      537,  542,  546,  534,  542,  546,  532,  531,  530,  466,
      482,  486,  556,  556,  556,  556,  559,  559,  559,  559,
      498,  529,  560,  561,  562,  560,  561,  562,  564,  526,
      525,  564,  524,  520,  560,  561,  562,  522,  521,  517,
      564,  569,  569,  569,  569,  569,  569,  569,  569,  569,
      569,  569,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  573,  573,  516,  573,  515,

      573,  574,  514,  513,  574,  512,  574,  575,  507,  575,
      575,  503,  575,  575,  575,  575,  575,  575,  576,  502,
      501,  500,  499,  576,  577,  577,  494,  577,  577,  577,
      577,  577,  577,  577,  577,  578,  489,  488,  578,  487,
      578,  579,  579,  579,  579,  485,  484,  483,  579,  579,
      579,  580,  580,  480,  479,  580,  580,  580,  580,  580,
      580,  580,  581,  478,  477,  581,  476,  581,  582,  582,
      474,  473,  582,  582,  582,  582,  582,  582,  582,  583,
      583,  470,  469,  468,  583,  583,  583,  583,  583,  583,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,

      584,  585,  585,  467,  585,  585,  585,  585,  585,  585,
      585,  585,  586,  586,  586,  465,  586,  586,  586,  586,
      586,  586,  586,  587,  587,  463,  462,  587,  587,  587,
      461,  587,  587,  587,  588,  588,  588,  460,  588,  588,
      588,  588,  588,  588,  588,  589,  589,  458,  457,  589,
      589,  589,  589,  589,  589,  589,  590,  590,  455,  590,
      590,  590,  590,  590,  590,  590,  590,  591,  591,  454,
      453,  591,  591,  591,  451,  591,  591,  591,  450,  448,
      446,  445,  444,  443,  441,  440,  439,  438,  437,  436,
      434,  433,  432,  429,  428,  427,  425,  424,  423,  422,

      420,  419,  418,  417,  416,  415,  414,  413,  412,  410,
      409,  406,  404,  402,  398,  397,  395,  394,  393,  391,
      388,  385,  384,  383,  382,  381,  379,  378,  377,  376,
      375,  374,  370,  369,  368,  366,  364,  363,  362,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  348,  347,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  334,
      331,  330,  329,  328,  327,  326,  325,  323,  322,  320,
      319,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  300,  299,  298,  297,  295,  294,  290,
      288,  287,  286,  285,  284,  283,  282,  281,  279,  277,

      276,  275,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  250,  249,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  223,  222,  221,
      220,  219,  218,  217,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      198,  195,  193,  192,  190,  187,  186,  185,  184,  183,
      174,  170,  169,  168,  167,  166,  165,  162,  161,  159,
      158,  149,  148,  147,  146,  145,  144,  143,  141,  140,

      139,  138,  135,  134,  133,  130,  128,  127,  126,  125,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  113,  112,  107,  105,  103,   87,   86,   84,   83,
       80,   72,   71,   70,   67,   60,   56,   55,   52,   50,
       46,   45,   43,   40,   39,   35,   31,   27,   26,   24,
       22,   18,   13,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,

      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[116] =
    {   0,
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int frontend_verilog_yy_flex_debug;
int frontend_verilog_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *frontend_verilog_yytext;
#line 1 "verilog_lexer.l"
/*
 *  yosys -- Yosys Open SYnthesis Suite
 *
 *  Copyright (C) 2012  Clifford Wolf <clifford@clifford.at>
 *  
 *  Permission to use, copy, modify, and/or distribute this software for any
 *  purpose with or without fee is hereby granted, provided that the above
 *  copyright notice and this permission notice appear in all copies.
 *  
 *  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 *  ---
 *
 *  The Verilog frontend.
 *
 *  This frontend is using the AST frontend library (see frontends/ast/).
 *  Thus this frontend does not generate RTLIL code directly but creates an
 *  AST directly from the Verilog parse tree and then passes this AST to
 *  the AST frontend library.
 *
 *  ---
 *
 *  A simple lexer for Verilog code. Non-preprocessor compiler directives are
 *  handled here. The preprocessor stuff is handled in preproc.cc. Everything
 *  else is left to the bison parser (see parser.y).
 *
 */
#line 36 "verilog_lexer.l"

#ifdef __clang__
// bison generates code using the 'register' storage class specifier
#pragma clang diagnostic ignored "-Wdeprecated-register"
#endif

#include "kernel/log.h"
#include "verilog_frontend.h"
#include "frontends/ast/ast.h"
#include "verilog_parser.tab.h"

USING_YOSYS_NAMESPACE
using namespace AST;
using namespace VERILOG_FRONTEND;

YOSYS_NAMESPACE_BEGIN
namespace VERILOG_FRONTEND {
	std::vector<std::string> fn_stack;
	std::vector<int> ln_stack;
}
YOSYS_NAMESPACE_END

#define SV_KEYWORD(_tok) \
	if (sv_mode) return _tok; \
	log("Lexer warning: The SystemVerilog keyword `%s' (at %s:%d) is not "\
			"recognized unless read_verilog is called with -sv!\n", frontend_verilog_yytext, \
			AST::current_filename.c_str(), frontend_verilog_yyget_lineno()); \
	frontend_verilog_yylval.string = new std::string(std::string("\\") + frontend_verilog_yytext); \
	return TOK_ID;

#define YY_INPUT(buf,result,max_size) \
	do { \
		lexin->read(buf, max_size-1); \
		result = lexin->gcount(); \
		if (result >= 0) buf[result] = '\0'; \
	} while (0)






#line 1023 "verilog_lexer.cc"

#define INITIAL 0
#define COMMENT 1
#define STRING 2
#define SYNOPSYS_TRANSLATE_OFF 3
#define SYNOPSYS_FLAGS 4
#define IMPORT_DPI 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int frontend_verilog_yylex_destroy (void );

int frontend_verilog_yyget_debug (void );

void frontend_verilog_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE frontend_verilog_yyget_extra (void );

void frontend_verilog_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *frontend_verilog_yyget_in (void );

void frontend_verilog_yyset_in  (FILE * in_str  );

FILE *frontend_verilog_yyget_out (void );

void frontend_verilog_yyset_out  (FILE * out_str  );

yy_size_t frontend_verilog_yyget_leng (void );

char *frontend_verilog_yyget_text (void );

int frontend_verilog_yyget_lineno (void );

void frontend_verilog_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int frontend_verilog_yywrap (void );
#else
extern int frontend_verilog_yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( frontend_verilog_yytext, frontend_verilog_yyleng, 1, frontend_verilog_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( frontend_verilog_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( frontend_verilog_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, frontend_verilog_yyin))==0 && ferror(frontend_verilog_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(frontend_verilog_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int frontend_verilog_yylex (void);

#define YY_DECL int frontend_verilog_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after frontend_verilog_yytext and frontend_verilog_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! frontend_verilog_yyin )
			frontend_verilog_yyin = stdin;

		if ( ! frontend_verilog_yyout )
			frontend_verilog_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			frontend_verilog_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				frontend_verilog_yy_create_buffer(frontend_verilog_yyin,YY_BUF_SIZE );
		}

		frontend_verilog_yy_load_buffer_state( );
		}

	{
#line 86 "verilog_lexer.l"


#line 1238 "verilog_lexer.cc"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of frontend_verilog_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 569 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1054 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = (yy_more_len); yyl < frontend_verilog_yyleng; ++yyl )
				if ( frontend_verilog_yytext[yyl] == '\n' )
					   
    frontend_verilog_yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 88 "verilog_lexer.l"
{
	fn_stack.push_back(current_filename);
	ln_stack.push_back(frontend_verilog_yyget_lineno());
	current_filename = frontend_verilog_yytext+11;
	frontend_verilog_yyset_lineno(0);
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 95 "verilog_lexer.l"
{
	current_filename = fn_stack.back();
	fn_stack.pop_back();
	frontend_verilog_yyset_lineno(ln_stack.back());
	ln_stack.pop_back();
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 102 "verilog_lexer.l"
{
	char *p = frontend_verilog_yytext + 5;
	while (*p == ' ' || *p == '\t') p++;
	frontend_verilog_yyset_lineno(atoi(p));
	while (*p && *p != ' ' && *p != '\t') p++;
	while (*p == ' ' || *p == '\t') p++;
	char *q = *p ? p + 1 : p;
	while (*q && *q != '"') q++;
	current_filename = std::string(p).substr(1, q-p-1);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 113 "verilog_lexer.l"
{
	log_error("Can't open include file `%s'!\n", frontend_verilog_yytext + 15);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 117 "verilog_lexer.l"
/* ignore timescale directive */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 119 "verilog_lexer.l"
{
	char *p = frontend_verilog_yytext;
	while (*p != 0 && *p != ' ' && *p != '\t') p++;
	while (*p == ' ' || *p == '\t') p++;
	if (!strcmp(p, "none"))
		VERILOG_FRONTEND::default_nettype_wire = false;
	else if (!strcmp(p, "wire"))
		VERILOG_FRONTEND::default_nettype_wire = true;
	else
		frontend_verilog_yyerror("Unsupported default nettype: %s", p);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 131 "verilog_lexer.l"
{
	frontend_verilog_yyerror("Unimplemented compiler directive or undefined macro %s.", frontend_verilog_yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 135 "verilog_lexer.l"
{ return TOK_MODULE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 136 "verilog_lexer.l"
{ return TOK_ENDMODULE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 137 "verilog_lexer.l"
{ return TOK_FUNCTION; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 138 "verilog_lexer.l"
{ return TOK_ENDFUNCTION; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 139 "verilog_lexer.l"
{ return TOK_TASK; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 140 "verilog_lexer.l"
{ return TOK_ENDTASK; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 141 "verilog_lexer.l"
{ return TOK_PARAMETER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 142 "verilog_lexer.l"
{ return TOK_LOCALPARAM; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 143 "verilog_lexer.l"
{ return TOK_DEFPARAM; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 144 "verilog_lexer.l"
{ return TOK_ASSIGN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 145 "verilog_lexer.l"
{ return TOK_ALWAYS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 146 "verilog_lexer.l"
{ return TOK_INITIAL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 147 "verilog_lexer.l"
{ return TOK_BEGIN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 148 "verilog_lexer.l"
{ return TOK_END; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 149 "verilog_lexer.l"
{ return TOK_IF; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 150 "verilog_lexer.l"
{ return TOK_ELSE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 151 "verilog_lexer.l"
{ return TOK_FOR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 152 "verilog_lexer.l"
{ return TOK_POSEDGE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 153 "verilog_lexer.l"
{ return TOK_NEGEDGE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 154 "verilog_lexer.l"
{ return TOK_OR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 155 "verilog_lexer.l"
{ return TOK_CASE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 156 "verilog_lexer.l"
{ return TOK_CASEX; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 157 "verilog_lexer.l"
{ return TOK_CASEZ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 158 "verilog_lexer.l"
{ return TOK_ENDCASE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 159 "verilog_lexer.l"
{ return TOK_DEFAULT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 160 "verilog_lexer.l"
{ return TOK_GENERATE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 161 "verilog_lexer.l"
{ return TOK_ENDGENERATE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 162 "verilog_lexer.l"
{ return TOK_WHILE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 163 "verilog_lexer.l"
{ return TOK_REPEAT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 165 "verilog_lexer.l"
{ SV_KEYWORD(TOK_ALWAYS); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 166 "verilog_lexer.l"
{ SV_KEYWORD(TOK_ALWAYS); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 167 "verilog_lexer.l"
{ SV_KEYWORD(TOK_ALWAYS); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 169 "verilog_lexer.l"
{ SV_KEYWORD(TOK_ASSERT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 170 "verilog_lexer.l"
{ SV_KEYWORD(TOK_PROPERTY); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 171 "verilog_lexer.l"
{ SV_KEYWORD(TOK_REG); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 172 "verilog_lexer.l"
{ SV_KEYWORD(TOK_REG); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 174 "verilog_lexer.l"
{ return TOK_INPUT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 175 "verilog_lexer.l"
{ return TOK_OUTPUT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 176 "verilog_lexer.l"
{ return TOK_INOUT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 177 "verilog_lexer.l"
{ return TOK_WIRE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 178 "verilog_lexer.l"
{ return TOK_REG; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 179 "verilog_lexer.l"
{ return TOK_INTEGER; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 180 "verilog_lexer.l"
{ return TOK_SIGNED; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 181 "verilog_lexer.l"
{ return TOK_GENVAR; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 182 "verilog_lexer.l"
{ return TOK_REAL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 184 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(frontend_verilog_yytext);
	return TOK_CONST;
}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 189 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(frontend_verilog_yytext);
	return TOK_CONST;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 194 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(frontend_verilog_yytext);
	return TOK_REALVAL;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 199 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(frontend_verilog_yytext);
	return TOK_REALVAL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 204 "verilog_lexer.l"
{ BEGIN(STRING); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 205 "verilog_lexer.l"
{ yymore(); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 206 "verilog_lexer.l"
{
	BEGIN(0);
	char *yystr = strdup(frontend_verilog_yytext);
	yystr[strlen(frontend_verilog_yytext) - 1] = 0;
	int i = 0, j = 0;
	while (yystr[i]) {
		if (yystr[i] == '\\' && yystr[i + 1]) {
			i++;
			if (yystr[i] == 'n')
				yystr[i] = '\n';
			else if (yystr[i] == 't')
				yystr[i] = '\t';
			else if ('0' <= yystr[i] && yystr[i] <= '7') {
				yystr[i] = yystr[i] - '0';
				if ('0' <= yystr[i + 1] && yystr[i + 1] <= '7') {
					yystr[i + 1] = yystr[i] * 8 + yystr[i + 1] - '0';
					i++;
				}
				if ('0' <= yystr[i + 1] && yystr[i + 1] <= '7') {
					yystr[i + 1] = yystr[i] * 8 + yystr[i + 1] - '0';
					i++;
				}
			}
		}
		yystr[j++] = yystr[i++];
	}
	yystr[j] = 0;
	frontend_verilog_yylval.string = new std::string(yystr);
	free(yystr);
	return TOK_STRING;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 237 "verilog_lexer.l"
{ yymore(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 239 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(frontend_verilog_yytext);
	return TOK_PRIMITIVE;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 244 "verilog_lexer.l"
{ return TOK_SUPPLY0; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 245 "verilog_lexer.l"
{ return TOK_SUPPLY1; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 247 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(frontend_verilog_yytext);
	return TOK_ID;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 252 "verilog_lexer.l"
{ return TOK_TO_SIGNED; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 253 "verilog_lexer.l"
{ return TOK_TO_UNSIGNED; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 255 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(std::string("\\") + frontend_verilog_yytext);
	return TOK_ID;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 260 "verilog_lexer.l"
{
	log("Warning: Found one of those horrible `(synopsys|synthesis) translate_off' comments.\n");
	log("It is strongly suggested to use `ifdef constructs instead!\n");
	BEGIN(SYNOPSYS_TRANSLATE_OFF);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 265 "verilog_lexer.l"
/* ignore synopsys translate_off body */
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 266 "verilog_lexer.l"
/* ignore synopsys translate_off body */
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 267 "verilog_lexer.l"
{ BEGIN(0); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 269 "verilog_lexer.l"
{
	BEGIN(SYNOPSYS_FLAGS);
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 272 "verilog_lexer.l"
{
	log("Warning: Found one of those horrible `(synopsys|synthesis) full_case' comments.\n");
	log("It is strongly suggested to use verilog x-values and default branches instead!\n");
	return TOK_SYNOPSYS_FULL_CASE;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 277 "verilog_lexer.l"
{
	log("Warning: Found one of those horrible `(synopsys|synthesis) parallel_case' comments.\n");
	log("It is strongly suggested to use verilog `parallel_case' attributes instead!\n");
	return TOK_SYNOPSYS_PARALLEL_CASE;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 282 "verilog_lexer.l"
/* ignore everything else */
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 283 "verilog_lexer.l"
{ BEGIN(0); }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 285 "verilog_lexer.l"
{
	BEGIN(IMPORT_DPI);
	return TOK_DPI_FUNCTION;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 290 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(std::string("\\") + frontend_verilog_yytext);
	return TOK_ID;
}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 295 "verilog_lexer.l"
/* ignore whitespaces */
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 297 "verilog_lexer.l"
{
	BEGIN(0);
	return *frontend_verilog_yytext;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 302 "verilog_lexer.l"
{
	return *frontend_verilog_yytext;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 306 "verilog_lexer.l"
{
	frontend_verilog_yylval.string = new std::string(frontend_verilog_yytext);
	return TOK_ID;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 311 "verilog_lexer.l"
{ return ATTR_BEGIN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 312 "verilog_lexer.l"
{ return ATTR_END; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 314 "verilog_lexer.l"
{ return DEFATTR_BEGIN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 315 "verilog_lexer.l"
{ return DEFATTR_END; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 317 "verilog_lexer.l"
{ return OP_POW; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 318 "verilog_lexer.l"
{ return OP_LOR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 319 "verilog_lexer.l"
{ return OP_LAND; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 320 "verilog_lexer.l"
{ return OP_EQ; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 321 "verilog_lexer.l"
{ return OP_NE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 322 "verilog_lexer.l"
{ return OP_LE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 323 "verilog_lexer.l"
{ return OP_GE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 325 "verilog_lexer.l"
{ return OP_EQX; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 326 "verilog_lexer.l"
{ return OP_NEX; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 328 "verilog_lexer.l"
{ return OP_NAND; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 329 "verilog_lexer.l"
{ return OP_NOR;  }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 330 "verilog_lexer.l"
{ return OP_XNOR; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 331 "verilog_lexer.l"
{ return OP_XNOR; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 333 "verilog_lexer.l"
{ return OP_SHL; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 334 "verilog_lexer.l"
{ return OP_SHR; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 335 "verilog_lexer.l"
{ return OP_SSHL; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 336 "verilog_lexer.l"
{ return OP_SSHR; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 338 "verilog_lexer.l"
{ return TOK_POS_INDEXED; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 339 "verilog_lexer.l"
{ return TOK_NEG_INDEXED; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 341 "verilog_lexer.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 342 "verilog_lexer.l"
/* ignore comment body */
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 343 "verilog_lexer.l"
/* ignore comment body */
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 344 "verilog_lexer.l"
{ BEGIN(0); }
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 346 "verilog_lexer.l"
/* ignore whitespaces */
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 347 "verilog_lexer.l"
/* ignore continuation sequence */
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 348 "verilog_lexer.l"
/* ignore one-line comments */
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 349 "verilog_lexer.l"
/* ignore simulation timings */
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 351 "verilog_lexer.l"
{ return *frontend_verilog_yytext; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 353 "verilog_lexer.l"
ECHO;
	YY_BREAK
#line 2007 "verilog_lexer.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(SYNOPSYS_TRANSLATE_OFF):
case YY_STATE_EOF(SYNOPSYS_FLAGS):
case YY_STATE_EOF(IMPORT_DPI):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed frontend_verilog_yyin at a new source and called
			 * frontend_verilog_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = frontend_verilog_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( frontend_verilog_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * frontend_verilog_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of frontend_verilog_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					frontend_verilog_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			frontend_verilog_yyrestart(frontend_verilog_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) frontend_verilog_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 569 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 569 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 568);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					frontend_verilog_yyrestart(frontend_verilog_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( frontend_verilog_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve frontend_verilog_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    frontend_verilog_yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void frontend_verilog_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        frontend_verilog_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            frontend_verilog_yy_create_buffer(frontend_verilog_yyin,YY_BUF_SIZE );
	}

	frontend_verilog_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	frontend_verilog_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void frontend_verilog_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		frontend_verilog_yypop_buffer_state();
	 *		frontend_verilog_yypush_buffer_state(new_buffer);
     */
	frontend_verilog_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	frontend_verilog_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (frontend_verilog_yywrap()) processing, but the only time this flag
	 * is looked at is after frontend_verilog_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void frontend_verilog_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	frontend_verilog_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE frontend_verilog_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) frontend_verilog_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in frontend_verilog_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) frontend_verilog_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in frontend_verilog_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	frontend_verilog_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with frontend_verilog_yy_create_buffer()
 * 
 */
    void frontend_verilog_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		frontend_verilog_yyfree((void *) b->yy_ch_buf  );

	frontend_verilog_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a frontend_verilog_yyrestart() or at EOF.
 */
    static void frontend_verilog_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	frontend_verilog_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then frontend_verilog_yy_init_buffer was _probably_
     * called from frontend_verilog_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void frontend_verilog_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		frontend_verilog_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void frontend_verilog_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	frontend_verilog_yyensure_buffer_stack();

	/* This block is copied from frontend_verilog_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from frontend_verilog_yy_switch_to_buffer. */
	frontend_verilog_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void frontend_verilog_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	frontend_verilog_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		frontend_verilog_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void frontend_verilog_yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)frontend_verilog_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in frontend_verilog_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)frontend_verilog_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in frontend_verilog_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE frontend_verilog_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) frontend_verilog_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in frontend_verilog_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	frontend_verilog_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to frontend_verilog_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       frontend_verilog_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE frontend_verilog_yy_scan_string (yyconst char * yystr )
{
    
	return frontend_verilog_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to frontend_verilog_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE frontend_verilog_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) frontend_verilog_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in frontend_verilog_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = frontend_verilog_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in frontend_verilog_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up frontend_verilog_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		frontend_verilog_yytext[frontend_verilog_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = frontend_verilog_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		frontend_verilog_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int frontend_verilog_yyget_lineno  (void)
{
        
    return frontend_verilog_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *frontend_verilog_yyget_in  (void)
{
        return frontend_verilog_yyin;
}

/** Get the output stream.
 * 
 */
FILE *frontend_verilog_yyget_out  (void)
{
        return frontend_verilog_yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t frontend_verilog_yyget_leng  (void)
{
        return frontend_verilog_yyleng;
}

/** Get the current token.
 * 
 */

char *frontend_verilog_yyget_text  (void)
{
        return frontend_verilog_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void frontend_verilog_yyset_lineno (int  line_number )
{
    
    frontend_verilog_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see frontend_verilog_yy_switch_to_buffer
 */
void frontend_verilog_yyset_in (FILE *  in_str )
{
        frontend_verilog_yyin = in_str ;
}

void frontend_verilog_yyset_out (FILE *  out_str )
{
        frontend_verilog_yyout = out_str ;
}

int frontend_verilog_yyget_debug  (void)
{
        return frontend_verilog_yy_flex_debug;
}

void frontend_verilog_yyset_debug (int  bdebug )
{
        frontend_verilog_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from frontend_verilog_yylex_destroy(), so don't allocate here.
     */

    /* We do not touch frontend_verilog_yylineno unless the option is enabled. */
    frontend_verilog_yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    frontend_verilog_yyin = stdin;
    frontend_verilog_yyout = stdout;
#else
    frontend_verilog_yyin = (FILE *) 0;
    frontend_verilog_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * frontend_verilog_yylex_init()
     */
    return 0;
}

/* frontend_verilog_yylex_destroy is for both reentrant and non-reentrant scanners. */
int frontend_verilog_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		frontend_verilog_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		frontend_verilog_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	frontend_verilog_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * frontend_verilog_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *frontend_verilog_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *frontend_verilog_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void frontend_verilog_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see frontend_verilog_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 353 "verilog_lexer.l"



// this is a hack to avoid the 'yyinput defined but not used' error msgs
void *frontend_verilog_avoid_input_warnings() {
	return (void*)&yyinput;
}


